name: todo_app
description: A simple and responsive To-Do List app built with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sembast: ^3.4.0
  sembast_web: ^2.0.1
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^16.1.0
  permission_handler: ^11.3.1
  timezone: ^0.9.2
  intl: ^0.20.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
