// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static Future<FirebaseOptions> get currentPlatform async {
    if (kIsWeb) {
      return web;
    }
    await Firebase.initializeApp(
      options: await DefaultFirebaseOptions.currentPlatform,
    );
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNv51aj-LqurU6D5-yqkho5UIT-rxdLlc',
    appId: '1:1093389860445:web:74a9ffdee9ce533dd397b4',
    messagingSenderId: '1093389860445',
    projectId: 'to-do-list-app-ef821',
    authDomain: 'to-do-list-app-ef821.firebaseapp.com',
    storageBucket: 'to-do-list-app-ef821.firebasestorage.app',
    measurementId: 'G-WW8KYG2K3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxB9pwMu5VElFj1Tz3vPznKxNP-qNOKFk',
    appId: '1:1093389860445:android:261c887b8d3dec8fd397b4',
    messagingSenderId: '1093389860445',
    projectId: 'to-do-list-app-ef821',
    storageBucket: 'to-do-list-app-ef821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL9ZNudo59GYpA5kj_5lDWTuYXy9DcyKU',
    appId: '1:1093389860445:ios:40e8f9e13114f08cd397b4',
    messagingSenderId: '1093389860445',
    projectId: 'to-do-list-app-ef821',
    storageBucket: 'to-do-list-app-ef821.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL9ZNudo59GYpA5kj_5lDWTuYXy9DcyKU',
    appId: '1:1093389860445:ios:40e8f9e13114f08cd397b4',
    messagingSenderId: '1093389860445',
    projectId: 'to-do-list-app-ef821',
    storageBucket: 'to-do-list-app-ef821.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNv51aj-LqurU6D5-yqkho5UIT-rxdLlc',
    appId: '1:1093389860445:web:f6a56658eabe798bd397b4',
    messagingSenderId: '1093389860445',
    projectId: 'to-do-list-app-ef821',
    authDomain: 'to-do-list-app-ef821.firebaseapp.com',
    storageBucket: 'to-do-list-app-ef821.firebasestorage.app',
    measurementId: 'G-KQ0B9BHWC0',
  );
}
